/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "./templates/**/*.{html,js,ts,jsx,tsx}",
    "./parts/**/*.{html,js,ts,jsx,tsx}",
    "./node_modules/vogelvlug-design-system/**/*.{html,js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      sm: "392px",
      md: "808px",
      lg: "1224px",
    },
    spacing: {
      0: "0",
      0.25: "0.25rem",
      0.5: "0.5rem",
      1: "1rem",
      1.5: "1.5rem",
      2: "2rem",
      3: "3rem",
      4: "4rem",
      5: "5rem",
      6: "6rem",
      7: "7rem",
      8: "8rem",
      9: "9rem",
      10: "10rem",
      column: "var(--column-base-width)",
      "column-base-gutter": "var(--column-base-gutter)",
      "column-2": "var(--column-multiple-2)",
      "column-3": "var(--column-multiple-3)",
      "column-4": "var(--column-multiple-4)",
      "column-5": "var(--column-multiple-5)",
      "column-6": "var(--column-multiple-6)",
      "column-8": "var(--column-multiple-8)",
      "column-10": "var(--column-multiple-10)",
      "column-12": "var(--column-multiple-12)",
    },
    borderRadius: {
      none: "0",
      sm: "0.25rem",
      DEFAULT: "0.5rem", // TODO: Move to figma
      lg: "1rem",
      full: "9999px",
    },
    colors: {
      base: {
        transparent: "transparent",
        white: "var(--base-white)",
        black: "var(--base-black)",
      },
      main: {
        100: "var(--main-100)",
        200: "var(--main-200)",
        300: "var(--main-300)",
        400: "var(--main-400)",
        500: "var(--main-500)",
        600: "var(--main-600)",
        700: "var(--main-700)",
      },
      accent: {
        100: "var(--accent-100)",
        200: "var(--accent-200)",
        300: "var(--accent-300)",
        400: "var(--accent-400)",
        500: "var(--accent-500)",
        600: "var(--accent-600)",
        700: "var(--accent-700)",
      },
      neutral: {
        100: "var(--neutral-100)",
        200: "var(--neutral-200)",
        300: "var(--neutral-300)",
        400: "var(--neutral-400)",
        500: "var(--neutral-500)",
        600: "var(--neutral-600)",
        700: "var(--neutral-700)",
      },
      success: {
        100: "var(--success-100)",
        200: "var(--success-200)",
        300: "var(--success-300)",
        400: "var(--success-400)",
        500: "var(--success-500)",
        600: "var(--success-600)",
        700: "var(--success-700)",
      },
      warning: {
        100: "var(--warning-100)",
        200: "var(--warning-200)",
        300: "var(--warning-300)",
        400: "var(--warning-400)",
        500: "var(--warning-500)",
        600: "var(--warning-600)",
        700: "var(--warning-700)",
      },
    },
    extend: {
      textColor: {
        default: "var(--text-default)",
        title: "var(--text-title)",
        subtitle: "var(--text-subtitle)",
        overtitle: "var(--text-overtitle)",
        "color-main": "var(--text-color-main)",
        "color-accent": "var(--text-color-accent)",
        caption: "var(--text-caption)",
        "fill-main-onfill": "var(--fill-main-onfill)",
        "fill-accent-onfill": "var(--fill-accent-onfill)",
      },
      backgroundColor: {
        transparent: "transparent",
        default: "var(--background-default)",
        subtle: "var(--background-subtle)",
        surface: "var(--surface-default)",
        "fill-main": "var(--fill-main)",
        "fill-main-hover": "var(--fill-main-hover)",
        "fill-accent": "var(--fill-accent)",
        "fill-accent-hover": "var(--fill-accent-hover)",
      },
      borderColor: {
        main: "var(--border-color-main)",
        accent: "var(--border-color-accent)",
        default: "var(--border-default)",
      },
    },
  },
  plugins: [],
};
