/**
 * Time constants in seconds
 */
export const SECOND_IN_SECONDS = 1;
export const MINUTE_IN_SECONDS = 60 * SECOND_IN_SECONDS;
export const HOUR_IN_SECONDS = 60 * MINUTE_IN_SECONDS;
export const DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS;
export const WEEK_IN_SECONDS = 7 * DAY_IN_SECONDS;
export const MONTH_IN_SECONDS = 30 * DAY_IN_SECONDS;
export const YEAR_IN_SECONDS = 365 * DAY_IN_SECONDS;

/**
 * Time constants in milliseconds
 */
export const MILLISECONDS_IN_MILLISECONDS = 1;
export const SECOND_IN_MILLISECONDS = 1000 * MILLISECONDS_IN_MILLISECONDS;
export const MINUTE_IN_MILLISECONDS = 60 * SECOND_IN_MILLISECONDS;
export const HOUR_IN_MILLISECONDS = 60 * MINUTE_IN_MILLISECONDS;
export const DAY_IN_MILLISECONDS = 24 * HOUR_IN_MILLISECONDS;
export const WEEK_IN_MILLISECONDS = 7 * DAY_IN_MILLISECONDS;
export const MONTH_IN_MILLISECONDS = 30 * DAY_IN_MILLISECONDS;
export const YEAR_IN_MILLISECONDS = 365 * DAY_IN_MILLISECONDS;
